#ifndef MODULE_CONFIG_H
#define MODULE_CONFIG_H

#define APP_ENABLE_UART_COMMAND 1
#define APP_ENABLE_BLUETOOTH    0
#define APP_ENABLE_OLED         1
#define APP_ENABLE_NRF24L01     1
#define APP_ENABLE_WIFI_MODULE  0
#define APP_ENABLE_ADC_POWER    0
#define APP_ENABLE_MOTOR        1
#define APP_ENABLE_SERVO        0

#define APP_ENABLE_TRANSPORT_UART       APP_ENABLE_UART_COMMAND
#define APP_ENABLE_TRANSPORT_NRF24L01   APP_ENABLE_NRF24L01
#define APP_ENABLE_TRANSPORT_BLUETOOTH  APP_ENABLE_BLUETOOTH
#define APP_ENABLE_TRANSPORT_WIFI       APP_ENABLE_WIFI_MODULE

#define APP_TRANSPORT_ENCRYPTION_NONE 0
#define APP_TRANSPORT_ENCRYPTION_LINK 1
#define APP_TRANSPORT_ENCRYPTION_APP  2

#define APP_TRANSPORT_UART_ENCRYPTION      APP_TRANSPORT_ENCRYPTION_NONE
#define APP_TRANSPORT_NRF24L01_ENCRYPTION  APP_TRANSPORT_ENCRYPTION_APP
#define APP_TRANSPORT_BLUETOOTH_ENCRYPTION APP_TRANSPORT_ENCRYPTION_LINK
#define APP_TRANSPORT_WIFI_ENCRYPTION      APP_TRANSPORT_ENCRYPTION_LINK

#define APP_UART_IMPL_INTERRUPT_RB 1
#define APP_UART_IMPL_DMA_IDLE     2
#define APP_UART_IMPL_POLLING      3
#define APP_UART_IMPL APP_UART_IMPL_INTERRUPT_RB

#define APP_SENSOR_IMPL_SIMULATED 1
#define APP_SENSOR_IMPL_ADC       2
#define APP_POWER_SENSOR_IMPL APP_SENSOR_IMPL_SIMULATED

#define APP_MOTION_IMPL_STATE_ONLY 1
#define APP_MOTION_IMPL_REAL_PWM   2
#define APP_MOTION_IMPL APP_MOTION_IMPL_REAL_PWM

#define APP_OLED_IMPL_NONE        0
#define APP_OLED_IMPL_SSD1306_SPI 1
#define APP_OLED_IMPL_SH1106_SPI  2
#define APP_OLED_IMPL_STUB        3
#define APP_OLED_IMPL APP_OLED_IMPL_SSD1306_SPI

#define APP_SPI_BUS_IMPL_HAL_BLOCKING 1
#define APP_SPI_BUS_IMPL_HAL_DMA      2
#define APP_SPI1_BUS_IMPL APP_SPI_BUS_IMPL_HAL_BLOCKING

#if (APP_UART_IMPL != APP_UART_IMPL_INTERRUPT_RB) && \
    (APP_UART_IMPL != APP_UART_IMPL_DMA_IDLE) && \
    (APP_UART_IMPL != APP_UART_IMPL_POLLING)
#error "Invalid APP_UART_IMPL"
#endif

#if (APP_POWER_SENSOR_IMPL == APP_SENSOR_IMPL_ADC) && !APP_ENABLE_ADC_POWER
#error "ADC power sensor implementation requires APP_ENABLE_ADC_POWER"
#endif

#if (APP_TRANSPORT_UART_ENCRYPTION < APP_TRANSPORT_ENCRYPTION_NONE) || \
    (APP_TRANSPORT_UART_ENCRYPTION > APP_TRANSPORT_ENCRYPTION_APP)
#error "Invalid UART transport encryption"
#endif

#endif
