#ifndef PIN_CONFIG_H
#define PIN_CONFIG_H

#define PIN_PORT_A 0U
#define PIN_PORT_B 1U

#define PIN_UART_CMD_TX_PORT PIN_PORT_A
#define PIN_UART_CMD_TX_PIN  9U
#define PIN_UART_CMD_RX_PORT PIN_PORT_A
#define PIN_UART_CMD_RX_PIN  10U

#define PIN_SPI1_SCK_PORT  PIN_PORT_A
#define PIN_SPI1_SCK_PIN   5U
#define PIN_SPI1_MISO_PORT PIN_PORT_A
#define PIN_SPI1_MISO_PIN  6U
#define PIN_SPI1_MOSI_PORT PIN_PORT_A
#define PIN_SPI1_MOSI_PIN  7U

#define PIN_OLED_CS_PORT  PIN_PORT_B
#define PIN_OLED_CS_PIN   0U
#define PIN_OLED_DC_PORT  PIN_PORT_B
#define PIN_OLED_DC_PIN   1U
#define PIN_OLED_RST_PORT PIN_PORT_B
#define PIN_OLED_RST_PIN  10U

#define PIN_NRF_CSN_PORT PIN_PORT_B
#define PIN_NRF_CSN_PIN  11U
#define PIN_NRF_CE_PORT  PIN_PORT_B
#define PIN_NRF_CE_PIN   12U
#define PIN_NRF_IRQ_PORT PIN_PORT_B
#define PIN_NRF_IRQ_PIN  13U

#define PIN_POWER_SENSE_PORT PIN_PORT_A
#define PIN_POWER_SENSE_PIN  0U
#define ADC_POWER_SENSE_CHANNEL 0U

#define MOTOR_TIMER_NUMBER      4U
#define MOTOR_PWM_PERIOD_COUNTS 999U
#define MOTOR_LEFT_IN1_CHANNEL  TIM_CHANNEL_1
#define MOTOR_LEFT_IN2_CHANNEL  TIM_CHANNEL_2
#define MOTOR_RIGHT_IN1_CHANNEL TIM_CHANNEL_3
#define MOTOR_RIGHT_IN2_CHANNEL TIM_CHANNEL_4

#define PIN_MOTOR_LEFT_IN1_PORT  GPIOB
#define PIN_MOTOR_LEFT_IN1_PIN   GPIO_PIN_6
#define PIN_MOTOR_LEFT_IN2_PORT  GPIOB
#define PIN_MOTOR_LEFT_IN2_PIN   GPIO_PIN_7
#define PIN_MOTOR_RIGHT_IN1_PORT GPIOB
#define PIN_MOTOR_RIGHT_IN1_PIN  GPIO_PIN_8
#define PIN_MOTOR_RIGHT_IN2_PORT GPIOB
#define PIN_MOTOR_RIGHT_IN2_PIN  GPIO_PIN_9

#endif
