#ifndef PIN_CONFIG_H
#define PIN_CONFIG_H

#define PIN_PORT_A 0U
#define PIN_PORT_B 1U
#define PIN_PORT_C 2U

#define PIN_UART_CMD_TX_PORT PIN_PORT_A
#define PIN_UART_CMD_TX_PIN  9U
#define PIN_UART_CMD_RX_PORT PIN_PORT_A
#define PIN_UART_CMD_RX_PIN  10U

#define PIN_SPI1_SCK_PORT  PIN_PORT_A
#define PIN_SPI1_SCK_PIN   5U
#define PIN_SPI1_MISO_PORT PIN_PORT_A
#define PIN_SPI1_MISO_PIN  6U
#define PIN_SPI1_MOSI_PORT PIN_PORT_A
#define PIN_SPI1_MOSI_PIN  7U

#define PIN_OLED_DC_PORT  PIN_PORT_B
#define PIN_OLED_DC_PIN   1U
#define PIN_OLED_RST_PORT PIN_PORT_B
#define PIN_OLED_RST_PIN  0U

#define PIN_NRF_CSN_PORT GPIOA
#define PIN_NRF_CSN_PIN  GPIO_PIN_4
#define PIN_NRF_CE_PORT  GPIOA
#define PIN_NRF_CE_PIN   GPIO_PIN_8
#define PIN_NRF_IRQ_PORT GPIOB
#define PIN_NRF_IRQ_PIN  GPIO_PIN_14

#define PIN_BLUETOOTH_TX_PORT GPIOB
#define PIN_BLUETOOTH_TX_PIN  GPIO_PIN_10
#define PIN_BLUETOOTH_RX_PORT GPIOB
#define PIN_BLUETOOTH_RX_PIN  GPIO_PIN_11

#define PIN_WIFI_TX_PORT GPIOA
#define PIN_WIFI_TX_PIN  GPIO_PIN_2
#define PIN_WIFI_RX_PORT GPIOA
#define PIN_WIFI_RX_PIN  GPIO_PIN_3
#define PIN_WIFI_EN_PORT GPIOB
#define PIN_WIFI_EN_PIN  GPIO_PIN_15

#define PIN_POWER_SENSE_PORT    GPIOA
#define PIN_POWER_SENSE_PIN     GPIO_PIN_0
#define ADC_POWER_SENSE_CHANNEL ADC_CHANNEL_0

#define MOTOR_TIMER_NUMBER      4U
#define MOTOR_PWM_PERIOD_COUNTS 999U
#define MOTOR_LEFT_IN1_CHANNEL  TIM_CHANNEL_1
#define MOTOR_LEFT_IN2_CHANNEL  TIM_CHANNEL_2
#define MOTOR_RIGHT_IN1_CHANNEL TIM_CHANNEL_3
#define MOTOR_RIGHT_IN2_CHANNEL TIM_CHANNEL_4

#define PIN_MOTOR_LEFT_IN1_PORT  GPIOB
#define PIN_MOTOR_LEFT_IN1_PIN   GPIO_PIN_6
#define PIN_MOTOR_LEFT_IN2_PORT  GPIOB
#define PIN_MOTOR_LEFT_IN2_PIN   GPIO_PIN_7
#define PIN_MOTOR_RIGHT_IN1_PORT GPIOB
#define PIN_MOTOR_RIGHT_IN1_PIN  GPIO_PIN_8
#define PIN_MOTOR_RIGHT_IN2_PORT GPIOB
#define PIN_MOTOR_RIGHT_IN2_PIN  GPIO_PIN_9

/* TIM2 partial remap 1: CH1/CH2/CH3/CH4 = PA15/PB3/PA2/PA3. */
#define SERVO_TIMER_NUMBER     2U
#define SERVO_PWM_FREQUENCY_HZ 50U
#define PIN_SERVO_1_PORT       GPIOA
#define PIN_SERVO_1_PIN        GPIO_PIN_15
#define PIN_SERVO_2_PORT       GPIOB
#define PIN_SERVO_2_PIN        GPIO_PIN_3
#define PIN_SERVO_3_PORT       GPIOA
#define PIN_SERVO_3_PIN        GPIO_PIN_2
#define PIN_SERVO_4_PORT       GPIOA
#define PIN_SERVO_4_PIN        GPIO_PIN_3

#define PIN_SWDIO_PORT GPIOA
#define PIN_SWDIO_PIN  GPIO_PIN_13
#define PIN_SWCLK_PORT GPIOA
#define PIN_SWCLK_PIN  GPIO_PIN_14

#endif
