#ifndef PIN_CONFIG_H
#define PIN_CONFIG_H

#define PIN_PORT_A 0U
#define PIN_PORT_B 1U

#define PIN_UART_CMD_TX_PORT PIN_PORT_A
#define PIN_UART_CMD_TX_PIN  9U
#define PIN_UART_CMD_RX_PORT PIN_PORT_A
#define PIN_UART_CMD_RX_PIN  10U

#define PIN_SPI1_SCK_PORT  PIN_PORT_A
#define PIN_SPI1_SCK_PIN   5U
#define PIN_SPI1_MISO_PORT PIN_PORT_A
#define PIN_SPI1_MISO_PIN  6U
#define PIN_SPI1_MOSI_PORT PIN_PORT_A
#define PIN_SPI1_MOSI_PIN  7U

#define PIN_OLED_CS_PORT  PIN_PORT_B
#define PIN_OLED_CS_PIN   0U
#define PIN_OLED_DC_PORT  PIN_PORT_B
#define PIN_OLED_DC_PIN   1U
#define PIN_OLED_RST_PORT PIN_PORT_B
#define PIN_OLED_RST_PIN  10U

#define PIN_NRF_CSN_PORT PIN_PORT_B
#define PIN_NRF_CSN_PIN  11U
#define PIN_NRF_CE_PORT  PIN_PORT_B
#define PIN_NRF_CE_PIN   12U
#define PIN_NRF_IRQ_PORT PIN_PORT_B
#define PIN_NRF_IRQ_PIN  13U

#define PIN_POWER_SENSE_PORT PIN_PORT_A
#define PIN_POWER_SENSE_PIN  0U
#define ADC_POWER_SENSE_CHANNEL 0U

#define SERVO_TIMER_NUMBER 4U
#define SERVO1_CHANNEL     1U
#define SERVO2_CHANNEL     2U
#define SERVO3_CHANNEL     3U
#define SERVO4_CHANNEL     4U

#endif
